

// TOOL:     vlog2tf
// DATE:     07/29/18  09:11:59 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   bb_decoder2to4
// DESIGN:   bb_decoder2to4
// FILENAME: bb_decoder2to4.tft
// PROJECT:  bb_learn
// VERSION:  1.0
// This file is auto generated by the ispLEVER

`timescale 1 ns / 1 ns

// Define Module for Test Fixture
module bb_decoder2to4_tf();

// Inputs
    reg [1:0] addrin;

// Outputs
    wire [3:0] yout;

// Instantiate the UUT
    bb_decoder2to4 UUT (
        .addrin(addrin), 
        .yout(yout)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            addrin = 0;
    end

    always
       #100 addrin = addrin + 1;

endmodule // bb_decoder2to4_tf