// TOOL:     vlog2tf
// DATE:     07/29/18  16:49:17 
// TITLE:    Lattice Semiconductor Corporation
// MODULE:   bb_shift
// DESIGN:   bb_shift
// FILENAME: bb_shift.tft
// PROJECT:  bb_learn
// VERSION:  1.0
// This file is auto generated by the ispLEVER

`timescale 1 ns / 1 ns

// Define Module for Test Fixture
module bb_shift_tf();

// Inputs
    reg clk;
    reg rst;

// Outputs
    wire [3:0] dout;

// Instantiate the UUT
    bb_shift UUT (
        .clk(clk), 
        .rst(rst), 
        .dout(dout)
        );


// Initialize Inputs
// You can add your stimulus here
    initial begin
            clk = 0;
            rst = 0;
     #680   rst = 1;
     #100   rst = 0;
    end

    always
      #50 clk = ~clk;

endmodule // bb_shift_tf
